---
kind: pipeline
type: docker
name: covid-central-2

steps:
- name: publish-backend
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: codeschneider/covid-central
    dockerfile: backend
