---
kind: pipeline
type: docker
name: default

steps:
# - name: publish-backend
#   image: plugins/docker
#   settings:
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#     repo: codeschneider/covid-central
#     dockerfile: backend/Dockerfile
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: codeschneider/covid-central-frontend
    context: frontend
    dockerfile: frontend/Dockerfile.prod
    
- name: deliver
  image: sinlead/drone-kubectl
   settings:
     kubernetes_server:
       from_secret: k8s_server
     kubernetes_cert:
       from_secret: k8s_cert
     kubernetes_token:
       from_secret: k8s_token
   commands:
     - kubectl apply -f deploy/deployment.yml
