---
kind: pipeline
type: docker
name: frontend

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: codeschneider/covid-central-frontend
    context: frontend
    dockerfile: frontend/Dockerfile.prod
- name: deliver
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl apply -f ./deploy/frontend.yml

---
kind: pipeline
type: docker
name: backend

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: codeschneider/covid-central
    context: backend
    dockerfile: backend/Dockerfile
- name: deliver
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl apply -f ./deploy/deployment.yml

---
kind: pipeline
type: docker
name: scraper

steps:
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: codeschneider/covid-central-scrape
    context: scraper
    dockerfile: scraper/Dockerfile
- name: deliver
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - kubectl apply -f ./deploy/scrape.yml
