version: "3.3"

networks:
  covid-central:
    driver: bridge

volumes:
  covid-central-data:
  redis-data:

services:
  mongo:
    container_name: mongo
    hostname: mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - covid-central-data:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=covid-central
      - MONGO_INITDB_ROOT_USERNAME=covid-central
      - MONGO_INITDB_ROOT_PASSWORD=covid-central
    networks:
      - covid-central

  redis:
    container_name: redis
    hostname: redis
    image: redis:4.0.10
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - covid-central

  # frontend:
  #   container_name: frontend
  #   hostname: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.prod
  #     args:
  #       PUBLIC_URL: /frontend
  #   volumes:
  #     - /app/node_modules
  #   environment:
  #     - PORT=3000
  #     - COVID_CENTRAL_API_URL=localhost/backend
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.port=3000"
  #     - "traefik.http.middlewares.frontend-stripprefix.stripprefix.prefixes=/frontend"
  #     - "traefik.http.routers.frontend.middlewares=frontend-stripprefix"
  #     - "traefik.http.routers.frontend.rule=PathPrefix(`/frontend`)"
  #     - "traefik.http.routers.frontend.entrypoints=web"
  #   networks:
  #     - covid-central

  backend:
    container_name: backend
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules/
    ports:
      - "1337:1337"
    entrypoint:
      - pm2-runtime
    command: app.js
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME=covid-central
      - MONGO_PASSWORD=covid-central
      - MONGO_HOSTNAME=mongo
      - MONGO_CONTAINER_PORT=27017
      - MONGO_DATABASE=covid-central
      - REDIS_HOSTNAME=redis
      - REDIS_CONTAINER_PORT=6379
      - FRONTEND_URL=http://localhost:3000
    labels:
      - "traefik.enable=true"
      - "traefik.port=1337"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/backend"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.routers.backend.rule=PathPrefix(`/backend`)"
      - "traefik.http.routers.backend.entrypoints=web"
    networks:
      - covid-central
    depends_on:
      - mongo

  traefik:
    image: "traefik:v2.1.2"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - covid-central
