apiVersion: v1
kind: Service
metadata:
  name: covid-central-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 1337
  selector:
    app: covid-central-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-central-api
  labels:
    app: covid-central-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: covid-central-api
  template:
    metadata:
      labels:
        app: covid-central-api
    spec:
      containers:
      - name: covid-central-api
        image: codeschneider/covid-central:latest
        imagePullPolicy: Always
        command: ["pm2-runtime", "app.js"]
        ports:
        - containerPort: 1337
          name: app
        env:
        - name: NODE_ENV
          value: production
        - name: MONGO_USERNAME
          value: test
        - name: MONGO_PASSWORD
          value: test
        - name: MONGO_HOSTNAME
          value: my-release-mongodb
        - name: MONGO_CONTAINER_PORT
          value: "27017"
        - name: MONGO_DATABASE
          value: test
        - name: REDIS_HOSTNAME
          value: my-redis-master
        - name: REDIS_CONTAINER_PORT
          value: "6379"
        - name: FRONTEND_URL
          value: https://covid-central.gatech.edu
