apiVersion: v1
kind: Service
metadata:
  name: covid-central-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 1337
  selector:
    app: covid-central-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # The name of our deployment
  name: covid-central-api
  # Kubernetes matches things up by labels,
  # So we give it a few ones to identify this deployment by
  labels:
    app: covid-central-api
spec:
  # We want 3 instances of the app running
  replicas: 3
  selector:
    matchLabels:
      app: covid-central-api
  template:
    metadata:
      labels:
        app: covid-central-api
    spec:
      containers:
      # Here is our actual definition for deployment
      - name: covid-central-api
        # Here we add the image we built earlier
        image: codeschneider/covid-central:{{DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        # We are still overriding for development,
        # Until we have added tls
        command: ["pm2-runtime", "app.js"]
        ports:
          # The port INSIDE the container
        - containerPort: 1337
          # A name for the port
          name: app
        env:
        - name: NODE_ENV
          value: production
        - name: MONGO_USERNAME
          value: test
        - name: MONGO_PASSWORD
          value: test
        - name: MONGO_HOSTNAME
          value: my-release-mongodb
        - name: MONGO_CONTAINER_PORT
          value: "27017"
        - name: MONGO_DATABASE
          value: test
        - name: REDIS_HOSTNAME
          value: my-redis-master
        - name: REDIS_CONTAINER_PORT
          value: "6379"
        - name: FRONTEND_URL
          value: https://covid.hdap.cloud
