apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid-central-scrape
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: covid-central-scrape
            image: codeschneider/covid-central-scrape:260602d
            imagePullPolicy: Always
          restartPolicy: OnFailure
