apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid-central-scrape
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: covid-central-scrape
            image: codeschneider/covid-central-scrape:{{DRONE_COMMIT_SHA}}
            imagePullPolicy: Always
          restartPolicy: OnFailure
